# If you come from bash you might have to change your $PATH.
#export PATH=$HOME/bin:/usr/local/bin:/$HOME/scripts

# Path to your oh-my-zsh installation.
export ZSH=~/.dotfiles/zsh/oh-my-zsh

# Sets terminal to use 256 color if it supports it
export TERM="xterm-256color"

#Powerlevel9k settings
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status disk_usage time )

#sets the default editor to vim
export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="agnoster"
ZSH_THEME="powerlevel9k/powerlevel9k"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=()

source $ZSH/oh-my-zsh.sh

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

########## ALIASES ##########
# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

source ~/.dotfiles/zsh/aliases

# if .secrets exists it sources the file in the private dir that contains passwords
# and other confidential information.
# the format is VARIABLE_NAME=value. One per line
# Ex. DB_USER="my_db_user"
# Ex. DB_PASS="db_pass_123!"
if [[ -e ~/.dotfiles/private/.secrets ]]; then
    source ~/.dotfiles/private/.secrets
fi

export PATH=/sbin:/bin:/usr/bin:$HOME/bin:/usr/local/bin:
source /home/beard/.dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
